DATA_DIR = "data"
RESIZED_DATA_DIR = "data-resize"

IMAGE_SUFFIX = "_img.nii"
MASK_SUFFIX = "_mask.nii"

RESIZE_DIMS = (256, 256, 32)

BATCH_SIZE = 1
NUM_WORKERS = 0
NORMALIZE = True

IN_CHANNELS = 1
OUT_CHANNELS = 1
UNET_FEATURES = (16, 32, 64, 128)

REPTILE_OUTER_STEPS = 200
REPTILE_INNER_STEPS = 3
REPTILE_INNER_LR = 1e-3
REPTILE_OUTER_LR = 1e-3
REPTILE_VAL_INTERVAL = 20

POS_WEIGHT = 5.0
